export const AGRUPAMENTO_BERCARIO = 'Berçário'
export const AGRUPAMENTO_MINI_GRUPO = 'Mini Grupo I e II'
export const AGRUPAMENTO_QUATRO_A_QUATORZE = '4 a 14 anos'

export const TIPO_ESTUDANTE_REDE = 'Estudante da Rede'
export const TIPO_ESTUDANTE_FORA_DA_REDE = 'Fora da Rede'

export const OPCOES_AGRUPAMENTO = [
  { value: AGRUPAMENTO_BERCARIO, label: AGRUPAMENTO_BERCARIO },
  { value: AGRUPAMENTO_MINI_GRUPO, label: AGRUPAMENTO_MINI_GRUPO },
  {
    value: AGRUPAMENTO_QUATRO_A_QUATORZE,
    label: AGRUPAMENTO_QUATRO_A_QUATORZE,
  },
]

export const OPCOES_TIPO_ESTUDANTE = [
  { value: TIPO_ESTUDANTE_REDE, label: TIPO_ESTUDANTE_REDE },
  { value: TIPO_ESTUDANTE_FORA_DA_REDE, label: TIPO_ESTUDANTE_FORA_DA_REDE },
]
