export { default as iconeCard1 } from './Icone-Card-1.png'
export { default as iconeCard2 } from './Icone-Card-2.png'
export { default as iconeCard3 } from './Icone-Card-3.png'
export { default as iconeCadastro } from './icone-cadastro.png'
export { default as iconeOlho } from './icone-olho.png'
export { default as iconeLapisEditar } from './icone-lapis-editar.png'
